# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0002_auto_20180717_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='File',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='FirstName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='LastName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='NormalFile',
            field=models.FileField(default=123, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemodel',
            name='TumorFile',
            field=models.FileField(default=123, upload_to=b''),
            preserve_default=False,
        ),
    ]
